### ISSUE TITLE
Accessing internal org repos 

### ISSUE THREAD

**Issue by vee-16** [jdoiro3/mkdocs-multirepo-plugin#116]
I'm currently using the mkdocs-multirepo-plugin to import multiple repositories into my MkDocs project. However, I've run into an issue when trying to access an internal organizational repository that requires authentication.

Do you currently support authentication for internal organizational repositories? If not, are there any workarounds for this?

**Comment by tomharrisonjr** [comment]
@vee-16 I am seeing this issue as well when connecting to a private repo. In my case, I am on macos, with homebrew, and `gh` (github CLI) installed, and also use 1Password's github plugin -- in both cases, the `GITHUB_TOKEN` value is not present in the environment.

When I `export GITHUB_TOKEN=<token>`, `mkdocs build` works successfully with this plugin.

I tend to think this is an issue with github, rather than the plugin. It's also the case that the `gh` CLI was hanging, as well. There have been recent changes to require MFA, so perhaps that's related?

**Comment by jdoiro3** [comment]
Have you seen the section on authentication in the README. I suggest looking at that as well as GitHub docs, assuming you're storing your repos there.
