### ISSUE TITLE
Check git version correctly

### ISSUE THREAD

**Issue by Sebastian-0** [jdoiro3/mkdocs-multirepo-plugin#150]
A bug was introduced in 0.8.1 were we say git versions < 2.25 support sparse clone which is the opposite of what was intended. See code snippet from `util.py`:
```python
def git_supports_sparse_clone() -> bool:
    """The sparse-checkout was added in 2.25.0
    See RelNotes here: https://github.com/git/git/blob/9005149a4a77e2d3409c6127bf4fd1a0893c3495/Documentation/RelNotes/2.25.0.txt#L67
    """
    return git_version() < Version(2, 25, 0)
```
I made a PR #149 which fixes this.

**Comment by jdoiro3** [comment]
https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/151 will fix this. Thanks for catching this quickly and apologies.

**Comment by jdoiro3** [comment]
Just merged the patch (`v0.8.1`). Can you confirm this fixes any errors you saw on your end, @Sebastian-0 ?

**Comment by jdoiro3** [comment]
I think it passed b/c all the test versions of `Git` used returned `False` when checking if it supported `sparse-clone`. The logic before `0.8.1` worked by chance and had quite a few bugs (all me). `0.8.1` improved version parsing but added a new bug where I was calling `ljust` for each `str` before converting to an `int` (a very careless change). Again, I think tests passed by chance, not because the logic was correct.

**Comment by Sebastian-0** [comment]
Yes it works now, thanks! I also did some debugging and found the `ljust` issue but you resolved it faster 😀

**Comment by jdoiro3** [comment]
Again, apologies. Been making a lot of careless mistakes lately.
