### ISSUE TITLE
Doesn't work when git installed with scoop (windows)

### ISSUE THREAD

**Issue by Hnasar** [jdoiro3/mkdocs-multirepo-plugin#50]
```sh
$ mkdocs serve
INFO     -  Building documentation...
INFO     -  Multirepo plugin importing docs...
🔳 my-custom-repo
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

it has to do with the code hardcoding bin/git.exe and bin/bash.exe

```
$ scoop which git
~\scoop\apps\git\current\cmd\git.exe
$ ls ~\scoop\apps\git\current\cmd\

    Directory: ~\scoop\apps\git\current\cmd

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           7/11/2022  2:32 PM         136752 git-gui.exe
-a---           7/11/2022  2:32 PM          45616 git.exe
-a---           7/11/2022  2:32 PM         136752 gitk.exe
-a---           7/11/2022  2:32 PM           3022 start-ssh-agent.cmd
-a---           7/11/2022  2:32 PM           2723 start-ssh-pageant.cmd
```

**Comment by nejch** [comment]
I guess this happens because scoop uses its own shims for git, and the plugin uses a custom discovery mechanism for the git binary (see below).

IMO, the plugin should assume that git is on PATH and instruct the user otherwise. There are so many ways to install git on windows - git-bash (git for windows), cygwin, msys2, wsl, PortableGit, chocolatey, scoop, etc. A lot of them have different approaches to install locations and it gets quite brittle. https://i.stack.imgur.com/apNVx.png is always fun to look at.

@jdoiro3 would you accept PRs that simply warn the user instead of trying to get a custom git path?

https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/76188e1999c8ebf992a530fa3c368f5731578030/mkdocs_multirepo_plugin/util.py#L65-L99
